const Data = [
    {
        ClassType : "yoga",
        Img_ID : 1,
        Img_Src : require("./TemplateImage/Yoga/yoga1.jpg").default,
        Location : "Chennai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "yoga",
        Img_ID : 2,
        Img_Src : require("./TemplateImage/Yoga/yoga2.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "yoga",
        Img_ID : 3,
        Img_Src : require("./TemplateImage/Yoga/yoga3.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "yoga",
        Img_ID : 4,
        Img_Src : require("./TemplateImage/Yoga/yoga4.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "yoga",
        Img_ID : 5,
        Img_Src : require("./TemplateImage/Yoga/yoga5.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "yoga",
        Img_ID : 6,
        Img_Src : require("./TemplateImage/Yoga/yoga6.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "chess",
        Img_ID : 7,
        Img_Src : require("./TemplateImage/Chess/chess1.jpg").default,
        Location : "Chennai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "chess",
        Img_ID : 8,
        Img_Src : require("./TemplateImage/Chess/chess2.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "chess",
        Img_ID : 9,
        Img_Src : require("./TemplateImage/Chess/chess3.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "chess",
        Img_ID : 10,
        Img_Src : require("./TemplateImage/Chess/chess4.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "chess",
        Img_ID : 11,
        Img_Src : require("./TemplateImage/Chess/chess5.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "chess",
        Img_ID : 12,
        Img_Src : require("./TemplateImage/Chess/chess6.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "gym",
        Img_ID : 13,
        Img_Src : require("./TemplateImage/Gym/gym1.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "gym",
        Img_ID : 14,
        Img_Src : require("./TemplateImage/Gym/gym2.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "gym",
        Img_ID : 15,
        Img_Src : require("./TemplateImage/Gym/gym3.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "gym",
        Img_ID : 16,
        Img_Src : require("./TemplateImage/Gym/gym4.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "gym",
        Img_ID : 17,
        Img_Src : require("./TemplateImage/Gym/gym5.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "gym",
        Img_ID : 18,
        Img_Src : require("./TemplateImage/Gym/gym6.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "boxing",
        Img_ID : 19,
        Img_Src : require("./TemplateImage/Boxing/boxing1.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "boxing",
        Img_ID : 20,
        Img_Src : require("./TemplateImage/Boxing/boxing2.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "boxing",
        Img_ID : 21,
        Img_Src : require("./TemplateImage/Boxing/boxing3.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "boxing",
        Img_ID : 22,
        Img_Src : require("./TemplateImage/Boxing/boxing4.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "boxing",
        Img_ID : 23,
        Img_Src : require("./TemplateImage/Boxing/boxing5.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "boxing",
        Img_ID : 24,
        Img_Src : require("./TemplateImage/Boxing/boxing6.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "driving",
        Img_ID : 25,
        Img_Src : require("./TemplateImage/Driving/driving1.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "driving",
        Img_ID : 26,
        Img_Src : require("./TemplateImage/Driving/driving2.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "driving",
        Img_ID : 27,
        Img_Src : require("./TemplateImage/Driving/driving3.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "driving",
        Img_ID : 28,
        Img_Src : require("./TemplateImage/Driving/driving4.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "driving",
        Img_ID : 29,
        Img_Src : require("./TemplateImage/Driving/driving5.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "driving",
        Img_ID : 30,
        Img_Src : require("./TemplateImage/Driving/driving6.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "cooking",
        Img_ID : 31,
        Img_Src : require("./TemplateImage/Cooking/cooking1.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "cooking",
        Img_ID : 32,
        Img_Src : require("./TemplateImage/Cooking/cooking2.jpg").default,
        Location : "Andhra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    { 
        ClassType : "cooking",
        Img_ID : 33,
        Img_Src : require("./TemplateImage/Cooking/cooking3.jpg").default,
        Location : "Maharastra",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "cooking",
        Img_ID : 34,
        Img_Src : require("./TemplateImage/Cooking/cooking4.jpg").default,
        Location : "Karnataka",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "cooking",
        Img_ID : 35,
        Img_Src : require("./TemplateImage/Cooking/cooking5.jpg").default,
        Location : "Mumbai",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    },
    {
        ClassType : "cooking",
        Img_ID : 36,
        Img_Src : require("./TemplateImage/Cooking/cooking6.jpg").default,
        Location : "Kerala",
        Timmings : "10.00 AM - 5.00 PM",
        Price : "$25 per month",
        Requirement : "16 or older",
        Experience : "Not Required",
        Cost : "$25 for class",
        caption : "AYUSH YOGA CENTER"
    }
]


export default Data